True True
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/simulation_script.py", line 98, in run_simulation_and_get_balance
    model_results_df, expobj = run_simulation(args)
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/simulation_script.py", line 92, in run_simulation
    model_os.run_model(till_termination=True)
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/aquacrop/core.py", line 298, in run_model
    self._initialize()
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/aquacrop/core.py", line 233, in _initialize
    self._clock_struct, self._param_struct = read_model_parameters(
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/aquacrop/initialize/read_model_parameters.py", line 109, in read_model_parameters
    crop = compute_crop_calendar(
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/aquacrop/initialize/compute_crop_calendar.py", line 129, in compute_crop_calendar
    temp_min = weather_df.MinTemp
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'MinTemp'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/compute_water_balance.py", line 72, in <module>
    main()
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/compute_water_balance.py", line 68, in main
    compute_balance_process(hourly, use_richards)
  File "/home/kpanthi/dev/thesis/aquacrop-richards/aquacrop/compute_water_balance.py", line 36, in compute_balance_process
    for result in executor.map(run_simulation_and_get_balance, allargs):
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/kpanthi/.conda/envs/drl/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
AttributeError: 'DataFrame' object has no attribute 'MinTemp'
